UI: Adds Resources details on home page
tektoncd/hub pull request #140
Opened 2020-12-01 03:43 UTC by PuneetPunamiya

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

2020-12-03 14:41 UTC, pratap0007 commented on ui/src/components/Cards/index.tsx
> +export const resourceName = (name: string, displayName: string) => {
exported variable name should start with capital letter

2020-12-03 14:44 UTC, pratap0007 commented on ui/src/components/Cards/index.tsx
> +                r
can we use resource instead of resources.items[r] ?

2020-12-03 14:57 UTC, pratap0007 commented on ui/src/components/Cards/index.tsx
> +                <div style={{ height: '2.5em' }}>
can you remove inline css ?

2020-12-08 07:02 UTC, vinamra28 requested changes

2020-12-08 07:02 UTC, vinamra28 commented on ui/src/store/resource.test.ts
> +        const displayName = store.resources.get('aws-cli')?.displayName;
I guess this should be :- 
```suggestion
        const displayName = store.resources.get('aws-cli')?.resourceName;
```

2020-12-08 07:32 UTC, PuneetPunamiya commented on ui/src/components/Icon/index.tsx
> -  return <div></div>;
I think we don't need that because we are handling the default case as unknown

2020-12-08 07:37 UTC, vinamra28 approved these changes
/lgtm

2020-12-09 06:26 UTC, vinamra28 commented on ui/src/components/Cards/Cards.test.tsx
> +describe('Resources', () => {
I guess this should be the test for `Cards`

2020-12-09 06:26 UTC, vinamra28 commented on ui/src/components/Cards/Cards.test.tsx
> +  it('should render the resources', (done) => {
how about `should render the resources on cards` or something like this?

2020-12-09 06:26 UTC, vinamra28 commented on ui/src/containers/Resources/index.tsx
> +    resources.isLoading === true ? (
since `isLoading` is a boolean variable so I guess we can remove `=== true`. WDYT?

2020-12-09 06:26 UTC, vinamra28 commented on ui/src/containers/Details/index.tsx
> +    resources.isLoading === true ? (
same as above

2020-12-09 09:10 UTC, vinamra28 reviewed
Thanks :+1: 
/lgtm

2020-12-09 09:25 UTC, pratap0007 commented
/lgtm
/approve
/meow

2020-12-09 09:27 UTC, merged