Adds Proxy Support for tkn hub commands
tektoncd/hub pull request #260
Opened 2021-05-13 09:05 UTC by sm43

This adds proxy support, the configuration must be defined in a file
at path `$HOME/.tekton/hub-config`.

The variable to be defined are:
HTTP_PROXY & HTTPS_PROXY:
	depending on the protocol of http call (http/https) it will look for the
variable in the file and use that for proxy. If hub config file or variable is
not found then it will not configure proxy and just move on.
It will error out if the url set for above variables is invalid.

This also support for variable `HUB_API_SERVER` which would be used
to provide api server url. By default the url is `https://api.hub.tekton.dev`.
URL can be passed by --api-server flag and it will take precedence over
url in config file and default url.

If url is not flag is not as passed, it will check in hub-config file,
if still not defined then it will use default url.

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

/cc @piyush-garg 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/main/CONTRIBUTING.md) for more details._

2021-06-28 04:58 UTC, vinamra28 requested changes
can we document this somewhere ?
maybe in `tkn hub --help` so that users are aware of this

2021-06-29 04:37 UTC, sm43 commented
@vinamra28 @piyush-garg PTAL :)

2021-06-29 05:14 UTC, vinamra28 reviewed
/lgtm

2021-07-07 07:18 UTC, PuneetPunamiya reviewed
/approve
/meow

2021-07-07 07:28 UTC, merged