Updates deployment configs to include the prefix `tekton-hub-`
tektoncd/hub pull request #379
Opened 2022-02-25 04:13 UTC by pratap0007

Sigend-off-by: Shiv Verma <shverma@redhat.com

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Run API Unit Tests, Lint Checks, API Design, Golden Files with `make api-check`
- [ ] Run UI Unit Tests, Lint Checks with `make ui-check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/main/CONTRIBUTING.md) for more details._

2022-02-25 04:39 UTC, PuneetPunamiya commented
/approve

2022-02-25 04:46 UTC, pratap0007 commented
/hold

2022-02-25 15:48 UTC, pratap0007 commented
/hold cancel

2022-02-28 11:41 UTC, vdemeester approved these changes
/cc @piyush-garg

2022-02-28 12:09 UTC, pratap0007 commented
/retest

2022-02-28 16:33 UTC, vinamra28 requested changes

2022-02-28 16:33 UTC, vinamra28 commented on config/04-kubernetes/40-auth-ingress.yaml
> +  name: tekton-hub-auth
can you please modify the line https://github.com/tektoncd/hub/blob/0937bdd758edcafc8599859c60074a6e9660cfa2/config/04-kubernetes/40-auth-ingress.yaml#L16 as well?

2022-02-28 16:33 UTC, vinamra28 commented on config/04-kubernetes/42-ui-ingress.yaml
> +  name: tekton-hub-ui
same as above

2022-02-28 16:33 UTC, vinamra28 commented on config/04-kubernetes/40-api-ingress.yaml
> +  name: tekton-hub-api
same as above

2022-03-01 03:13 UTC, sm43 commented
this changes won't be backward compatible right? 🤔

2022-03-01 03:14 UTC, vinamra28 commented
> this changes won't be backward compatible right? thinking

nope

2022-03-01 03:15 UTC, vinamra28 commented on config/00-init/02-db-pvc.yaml
> +    app: tekton-hub-db
do we want to change the value of the labels as well?
cc @PuneetPunamiya @piyush-garg @sm43

2022-03-01 03:21 UTC, sm43 commented
we need to document this, how to replace existing deployment with this changes
and include in release notes

2022-03-04 07:43 UTC, sm43 commented
/lgtm

2022-03-04 07:55 UTC, merged